function sl_postprocess(h)
%

%   Copyright 2025 The MathWorks, Inc.

ft = { {'acoustical_lib/Acoustical Elements/Inertance', ...
        'acoustic_lib/Acoustical Elements/Inertance',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/Medium parameters', ...
        'acoustic_lib/Acoustical Elements/Medium Parameters',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/Acoustical Reference', ...
        'acoustic_lib/Acoustical Elements/Acoustical Reference',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/Compliance', ...
        'acoustic_lib/Acoustical Elements/Compliance',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/Resistor', ...
        'acoustic_lib/Acoustical Elements/Resistor',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/Variable Resistor', ...
        'acoustic_lib/Acoustical Elements/Variable Resistor',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/Acoustical transformer', ...
        'acoustic_lib/Transformers/Acoustical Transformer',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/Mechanical to Acoustical Converter (area transformer).', ...
        'acoustic_lib/Transformers/Mechanical to Acoustical Converter (Area Transformer)',...
        'acoustical.UpdateSourceFile'}
         ...
        {'acoustical_lib/Acoustical Sensors/Pressure Sensor', ...
        'acoustic_lib/Acoustical Sensors/Pressure Sensor',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Sensors/Volume velocity Sensor', ...
        'acoustic_lib/Acoustical Sensors/Volume Velocity Sensor',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Sources/Controlled Pressure Source', ...
        'acoustic_lib/Acoustical Sources/Controlled Pressure Source',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Sources/Controlled Volume Velocity Source', ...
        'acoustic_lib/Acoustical Sources/Controlled Volume Velocity Source',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Sources/General Pressure Source', ...
        'acoustic_lib/Acoustical Sources/General Pressure Source',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Sources/Volume Velocity Source', ...
        'acoustic_lib/Acoustical Sources/Volume Velocity Source',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Acoustical Elements/P_ff - far field pressure referenced to 1m in Pa', ...
        'acoustic_lib/Acoustical Sensors/Far Field Pressure',...
        'acoustical.UpdateSourceFile'} 
        ...
        {'acoustical_lib/Enclosures/Simple acoustical enclosure', ...
        'acoustic_lib/Applications/Cavities and Enclosures/Simple Acoustical Enclosure',...
        'acoustical.UpdateSourceFile'} 
        ...
        {'acoustical_lib/Moving Coil Speakers/speaker_nonlinear_blocks/Loudspeaker converter with variable BL', ...
        'acoustic_lib/Applications/Moving Coil Speakers/Nonlinear Blocks/Loudspeaker Converter With Variable BL',...
        'acoustical.UpdateSourceFile'} 
        ...
        {'acoustical_lib/Moving Coil Speakers/speaker_nonlinear_blocks/Nonlinear Translational Spring', ...
        'acoustic_lib/Applications/Moving Coil Speakers/Nonlinear Blocks/Nonlinear Translational Spring',...
        'acoustical.UpdateSourceFile'} 
        ...
        {'acoustical_lib/Moving Coil Speakers/speaker_nonlinear_blocks/Nonlinear Inductor', ...
        'acoustic_lib/Applications/Moving Coil Speakers/Nonlinear Blocks/Nonlinear Inductor',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Moving Coil Speakers/speaker_nonlinear_blocks/Nonlinear Translational Damper', ...
        'acoustic_lib/Applications/Moving Coil Speakers/Nonlinear Blocks/Nonlinear Translational Damper',...
        'acoustical.UpdateSourceFile'}      
        ...
        {'acoustical_lib/hidden/thermovisc_Ydl', ...
        'acoustic_lib/Hidden/thermovisc_Ydl',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/hidden/thermovisc_Zdl', ...
        'acoustic_lib/Hidden/thermovisc_Zdl',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/hidden/Ydl_tv_cyl', ...
        'acoustic_lib/Hidden/Ydl_tv_cyl',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/hidden/Ydl_tv_plates', ...
        'acoustic_lib/Hidden/Ydl_tv_plates',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/hidden/Zdl_tv_cyl', ...
        'acoustic_lib/Hidden/Zdl_tv_cyl',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/hidden/Zdl_tv_plates', ...
        'acoustic_lib/Hidden/Zdl_tv_plates',...
        'acoustical.UpdateSourceFile'}
        ...
        {'acoustical_lib/Tubes and Horns/tube_w_loss - lossy cylindrical tube with N segments', ...
        'acoustic_lib/Applications/Tubes and Horns/Lossy Cylindrical Tube With N Segments',...
        'acoustical.UpdateSourceFile'} 
        ...
        {'acoustical_lib/Tubes and Horns/tube_tv_plates - thin rectangular tube with thermoviscous losses', ...
        'acoustic_lib/Applications/Tubes and Horns/Thin Rectangular Tube With Thermoviscous Losses',...
        'acoustical.UpdateSourceFile'} 

        };

set_param(h, 'ForwardingTable', ft);

end
